spring.application.name=student-management
server.port=8080

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/SpringBoot
spring.datasource.username=postgres
spring.datasource.password=Bannu@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Logging Configuration
logging.level.root=INFO
logging.level.com.training.employee_management=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n